### ISSUE TITLE
Setting room Topic

### ISSUE THREAD

**Issue by stefanalund** [matrix-org/matrix-angular-sdk#4]
I was trying to set the room Topic from a user that did not have permission to set it. Why show that button at all in this scenario?

**Comment by ara4n** [comment]
Right - that's precisely the sort of UX polish we're working on it currently; we haven't done much work with respect to managing room permissions on iOS yet. This is probably best filed as a feature request in jira btw so the dev team can directly pick it up.

We'll continue to try to repro the emoji crash.

**Comment by bnvk** [comment]
Opened this as [JIRA issue](https://matrix.org/jira/browse/SYWEB-327) so can be closed here!

**Comment by Kegsay** [comment]
Closed as per request.
